agent:
  model:
    name: openai/gpt-4.1
    per_instance_cost_limit: 0.5
    total_cost_limit: 2.0
    per_instance_call_limit: 50
    max_input_tokens: 1047576
    completion_kwargs:
      parallel_tool_calls: false
  tools:
    env_variables:
      MODEL_NAME: gpt-4.1